#include "ShaderSemantics.h"



namespace V
{
	CGGLenum shaderMatrixMap[] = 
	{
		CG_GL_MODELVIEW_MATRIX,
		CG_GL_PROJECTION_MATRIX,
		CG_GL_TEXTURE_MATRIX,
		CG_GL_MODELVIEW_PROJECTION_MATRIX
	};

	CGGLenum shaderTransformMap[] = 
	{
		CG_GL_MATRIX_IDENTITY,
		CG_GL_MATRIX_INVERSE,
		CG_GL_MATRIX_TRANSPOSE,
		CG_GL_MATRIX_INVERSE_TRANSPOSE
	};
}